### Atualiza um portfólio existente pelo ID
PUT http://localhost:8000/portfolios/6a267bfca6
Content-Type: application/json

{
  "code": "6a267bfca6",
  "name": "Meu Portfólio Atualizado",
  "description": "Descrição."
}

###