GET http://127.0.0.1:9000/finances/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJyb2Jzb252bnQiLCJleHAiOjE3MDA5NTYxNzh9.aR4qiCarNHGZ8dghm15zek7o5PfA8Jt3dRisNjWGHiY