GET http://127.0.0.1:8000/api/finances/consolidations?month=12/2023&=&account_codes=bmjdpUTgZm&account_codes=Z5Oym4HHWo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJyb2Jzb252bnQiLCJleHAiOjE3MDE3MjU3NTl9.8cYAK4YOVmnr3YPkmIG19L7G3i-dgPj1CARkTxfroVU