"""Criação da tabela finances_account_consolidations

Revision ID: 6d8e168be246
Revises: 297cd5110eb4
Create Date: 2023-12-03 12:01:56.612890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6d8e168be246'
down_revision: Union[str, None] = '297cd5110eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'finances_account_consolidations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_code', sa.String(), nullable=True),
        sa.Column('month', sa.Date(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_code', 'month', name='finances_account_consolidations_account_month_uc')
    )
    op.create_index(op.f('ix_finances_account_consolidations_account_code'), 'finances_account_consolidations',
                    ['account_code'], unique=True)
    op.create_index(op.f('ix_finances_account_consolidations_id'), 'finances_account_consolidations', ['id'],
                    unique=True)

    op.create_foreign_key(
        'fk_finances_account_consolidations_account_code',
        'finances_account_consolidations',
        'finances_accounts',
        ['account_code'],
        ['code']
    )


def downgrade():
    op.drop_table('finances_account_consolidations')
