### Obtém os detalhes de um portfólio específico pelo ID
GET http://127.0.0.1:9000/portfolios
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJyb2Jzb252bnQiLCJleHAiOjE3MDEyNzM1Mjh9.m4ffv8FYn_hJJA7qFxllDgBpGWRJaXD9VLg8v3dHHSI

###