GET https://my-investments.home.robsonvnt.me/api/portfolios/heueWALW3h/investments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJyb2Jzb252bnQiLCJleHAiOjE3MDA1MTAyMDh9.vzgV8LXnmFrMd1ODFzbAkBVd3AllJYq8c5j_YH0Hh74