POST http://localhost:8000/portfolios/6a267bfca6/investments
Content-Type: application/json

{
  "portfolio_code": "6a267bfca6",
  "asset_type": "STOCK",
  "ticker": "PETR6",
  "quantity": 400,
  "purchase_price": 34.23,
  "purchase_date": "1988-02-05",
  "current_average_price": 34.23
}


