### Atualiza um investimento existente
PUT http://192.168.0.2/api/portfolios/a196b8782e/investments/82cf5f1db9 HTTP/1.1
Content-Type: application/json

{
  "code": "82cf5f1db9",
  "portfolio_code": "6a267bfca6",
  "asset_type": "STOCK",
  "ticker": "AAPL",
  "quantity": 15,
  "purchase_price": 160,
  "current_average_price": 160,
  "purchase_date": "2023-10-21"
}
